# Model
model: "vanilla_ResNet"
pretrained: False
freeze_layers: True
# Custom model
resnet_size: 18
# Dataset
dataset_name: "fmow"
num_classes: 62
batch_size: 8
loader_normalized: False
# Optimization
loss_criterion: "cross-entropy"
num_epochs: 20
learning_rate: 0.01
momentum: 0.9
weight_decay: 1e-4
# Loss
reg_lambda: 0 #0.001
upweighting: False
# ckpt_interval: 1
# optim.lr_scheduler
# lr_scheduler_step_size: 50
# lr_scheduler_gamma: 0.1