# Model
model: "vanilla_ResNet"
pretrained: False
freeze_layers: False
# Custom model
resnet_size: 18
# Dataset
dataset_name: "camelyon17"
num_classes: 1
batch_size: 32
# Optimization
loss_criterion: "binary-cross-entropy"
num_epochs: 5
learning_rate: 0.01
momentum: 0.9
weight_decay: 1e-4
# Loss
reg_lambda: 0 #0.001
dann_trade_off: 1
# ckpt_interval: 1
# optim.lr_scheduler
# lr_scheduler_step_size: 50
# lr_scheduler_gamma: 0.1